office-for-students/beta-data-pipelines

EtlPipelineBlobTrigger/host.json, IngestRawXmlHttpTrigger/host.json
See title
Check bundle exists and functions builds locally
=> Add extension bundle to azure functions

EtlPipelineBlobTrigger/requirements.txt, IngestRawXmlHttpTrigger/requirements.txt
See title
Check you can still build the functions locally
=> Add requirements file to each function app

host.json
Extend the functions processing time out from 30minutes to 1hour.
Unless you are willing to run azure function locally on a slow internet connection, there is not much to test.
=> Extend the functions processing time out

docs/STATISTICS.md
Missing institution course salary stats and previously misinterpreted sector course salary stats for the institution course salary stats.
Check changes make sense
=> Update documentation on LEO and Salary statistics

EtlPipelineBlobTrigger/course_docs.py
Skip get locations when LOCID is missing and throw a warning to investigate later
Check logic makes sense
=> Skip get locations when LOCID is missing

docs/INSTITUTION.md
Update institution resource documentation. Includes array of student_union links and their corresponding location name.
Check documentation makes sense
=> Include student_unions array to institution resource documentation

CreateUkrlpBlobTrigger/lookup_creator.py
Set PYTHONPATH so SharedCode can be found
Review the changes and test.
=> Set PYTHONPATH so SharedCode can be found

azure-pipelines.yml, dev-azure-pipelines.yml, prod-azure-pipelines.yml
Fix the ci builds
Check pr is set to none across pipelines
=> Update ci builds

docs/COURSE.md
Document new field (course cost url) in xml
Check documentation makes sense
=> Add course cost url to docs

CourseSearchBuilderBlobTrigger/search.py
PUT may return 201 if the SynonymMap does not exist. We need to check for this.
From rfc7231: 
"The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload".
Review the changes.
Test
=> Check for HTTP status 201 which may be returned by PUT

EtlPipelineBlobTrigger/lookup_files/unavailreason_welsh.json, EtlPipelineBlobTrigger/tests/fixtures/course_cont_subj_resp.json, EtlPipelineBlobTrigger/tests/fixtures/course_nhs_subj_resp.json, EtlPipelineBlobTrigger/tests/fixtures/course_no_sal_subj_resp.json, EtlPipelineBlobTrigger/tests/fixtures/course_nss_subj_resp.json, EtlPipelineBlobTrigger/tests/fixtures/course_sal_subj_resp.json, EtlPipelineBlobTrigger/tests/fixtures/course_three_commons.json, EtlPipelineBlobTrigger/tests/fixtures/one_inst_one_course.json, EtlPipelineBlobTrigger/tests/fixtures/one_inst_one_course_with_crsecsturl.json, EtlPipelineBlobTrigger/tests/fixtures/tariff_get_stats_resp_with_subj.json
Fix unicode substitutions as advised by Gordon's contact.
Review changes.
=> Updates for char encoding tests

CreateInstBlobTrigger/institution_docs.py
See title
Review changes - check an institution such as 99999999 in the pre-prod institutions table
=> Handle UKRLP docs without contact details

CourseSearchBuilderBlobTrigger/search.py
Add statistics to mathematics synonym. Also includes stat, stats and statistic
Check synonyms have been added
=> Add statistics to mathematics synonym

.gitignore
Do not want files containing secret keys uploaded to github
Should contain local.settings.json.*
=> Add local setting files to gitignore

EtlPipelineBlobTrigger/course_lookup_tables.py
=> Fixed distance learning typo.

CourseSearchBuilderBlobTrigger/tests/fixtures/input-full-fat-course.json, CourseSearchBuilderBlobTrigger/tests/fixtures/output-full-fat-course.json, EtlPipelineBlobTrigger/tests/fixtures/one_inst_one_course.json, EtlPipelineBlobTrigger/tests/fixtures/one_inst_one_course_with_crsecsturl.json, EtlPipelineBlobTrigger/tests/test_enricher.py, EtlPipelineBlobTrigger/ukrlp_enricher.py, EtlPipelineBlobTrigger/validators.py
=> Fixed additional typos

CreateUkrlpBlobTrigger/lookup_creator.py
=> Removed Bulk Insert for profiling.

CreateInstBlobTrigger/institution_docs.py, CreateUkrlpBlobTrigger/lookup_creator.py, EtlPipelineBlobTrigger/course_docs.py
=> Added delay after bulk import to prevent CosmosDB timeout

host.json
=> Updated host.json to use latest Azure Extensions Bundle version

host.json
=> Adjusted version.

host.json
=> Removed trailing whitespace

CreateDataSet/__init__.py, CreateDataSet/function.json
=> Replaced CreateDataSet timer trigger with HTTP triigger

CreateDataSet/__init__.py
=> Removed response

CreateDataSet/__init__.py, CreateInst/__init__.py, CreateUkrlp/__init__.py, EtlPipeline/__init__.py, PostcodeSearchBuilder/__init__.py, SubjectBuilder/__init__.py
=> Added automated e-mails to PostcodeSearchBuilder and SubjectBuilder

CourseSearchBuilder/__init__.py, CreateInst/__init__.py, CreateUkrlp/__init__.py, EtlPipeline/__init__.py, README.md
=> Updated documentation and some variable locations.

CreateDataSet/__init__.py, PostcodeSearchBuilder/__init__.py, SubjectBuilder/__init__.py
=> Fixed function names in e-mail

CreateDataSet/dataset_creator.py, CreateDataSet/tests/test_dataset_creator.py, CreateInst/__init__.py, CreateInst/dev-test-scripts/test-inst-docs.py, CreateInst/institution_docs.py, CreateInst/tests/test_institution_docs.py, CreateUkrlp/__init__.py, CreateUkrlp/function.json, CreateUkrlp/lookup_creator.py, EtlPipeline/build_institutions_json.py, EtlPipeline/course_docs.py, EtlPipeline/subject_enricher.py, EtlPipeline/tests/test_enricher.py, EtlPipeline/ukrlp_enricher.py, SharedCode/blob_helper.py, SharedCode/dataset_helper.py, SharedCode/mail_helper.py, SharedCode/tests/test_dataset_helper.py, SharedCode/utils.py, SubjectBuilder/__init__.py, SubjectBuilder/database.py, SubjectBuilder/exceptions.py, SubjectBuilder/function.json, SubjectBuilder/models.py, docs/DATASET.md
=> Added subject bulder in pipeline.

CreateUkrlp/__init__.py, CreateUkrlp/dev-test-scripts/test-lookup-creator.py, CreateUkrlp/lookup_creator.py, CreateUkrlp/tests/test_lookup_creator.py
=> Refactored UKRLP Lookup Creator

CourseSearchBuilder/__init__.py, CourseSearchBuilder/build_institutions_json.py, CourseSearchBuilder/build_version_json.py
=> Added version.json builder

EtlPipeline/ukrlp_enricher.py
=> Refactored get_urklp_welsh_name

EtlPipeline/subject_enricher.py
=> Merge request

EtlPipeline/course_stats.py
=> Modified SharedUtils to only get subject codes once

EtlPipeline/__init__.py
=> Added eexception details to EtlPipeline

EtlPipeline/course_stats.py
=> Added logging information to Shared Utils

EtlPipeline/subject_enricher.py
=> Removed string conversion on database subject level

CourseSearchBuilder/models.py, CourseSearchBuilder/schemas/course.json, CourseSearchBuilder/tests/fixtures/input-full-fat-course.json, CourseSearchBuilder/tests/fixtures/output-full-fat-course.json, EtlPipeline/course_docs.py, EtlPipeline/qualification_enricher.py, README.md, docs/COURSE.md
=> Added qualification level to course docs and search index.

CreateUkrlp/ukrlp_client.py, EtlPipeline/course_docs.py
Merge to develop for 2020 go-live release.
=> Sept 20 sprint 6

CourseSearchBuilder/build_institutions_json.py, CourseSearchBuilder/tests/fixtures/indexes.json, CreateInst/tests/test_ukrlp_contact_details.py
=> Sjh remove university for

CourseSearchBuilder/build_sitemap_xml.py
Resolve error on xml generation
=> small reformat - encode xml_file before writing to the blob

CourseSearchBuilder/build_institutions_json.py
Added function for adding institutions_en.json
Added first_trading_name, legal_name and other_names to build json function
Deploy to pre-prod and see if files get generated
=> update to function to create institutions.json files

CourseSearchBuilder/build_institutions_json.py, CourseSearchBuilder/tests/test_build_institutions.py
=> added test for build institutions, handled keys not existing

CourseSearchBuilder/build_institutions_json.py
Describe what you have changed and why.
Describe the steps required to test the changes.
=> fixed key issues with json file

EtlPipeline/sector_salaries.py
did str(int()) to the kis mode and kis level in sector salaries also
=> Sector leading zero
